<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" type="text/css" href="/plugs/layui/css/layui.css"/>
    <link rel="stylesheet" type="text/css" href="/css/base.css?2"/>
    <style>
        .top{
            height: 80px;
        }
        .top .log{
            height: 70px;
            background: url(http://mysqltutorial.org//wp-content/uploads/2016/01/mysqltutorial.png) no-repeat left center;
        }
        .top .log a{
            display: block;
            float: left;
            min-height: 60px;
            text-indent: -9999px;
            width: 100%;
        }
        .top .nav{
            height: 80px;
            line-height: 80px;
        }

        .main{
            margin-top: 10px;
        }
        .main .left{
            width: 73%;
            margin-right: 2%;
        }
        .main .right{
            width: 25%;
        }
        .layadmin-serach-list li{
            display: flex;
            flex-direction: row;
            margin: 20px 0;
        }
        .layadmin-serach-list li .layui-serachlist-cover img{
            width: 60px;
        }
        .layadmin-serach-list li .layui-serachlist-text{
            margin: 0 10px;
        }

        .fancy-list dt{
            margin-top: 20px;
        }
    </style>
</head>
<body>

<div class="top layui-bg-green">
    <div class="layui-container">
        <div class="layui-row">
            <div class="layui-col-md3 log">
                <a href="http://www.mysqltutorial.org/">MySQL Tutorial</a>
            </div>
            <div class="layui-col-md8 layui-col-lg-offset1">
                <ul class="layui-nav layui-bg-green nav" lay-filter="">
                    <li class="layui-nav-item"><a href="">首页</a></li>
                    <li class="layui-nav-item"><a href="">开始</a></li>
                    <li class="layui-nav-item"><a href="">基础</a></li>
                    <li class="layui-nav-item">
                        <a href="javascript:;">高级</a>
                        <dl class="layui-nav-child"> <!-- 二级菜单 -->
                            <dd><a href="">MYSQL 存储过程</a></dd>
                            <dd><a href="">MYSQL 视图</a></dd>
                            <dd><a href="">MYSQL 触发器</a></dd>
                            <dd><a href="">MYSQL 事件</a></dd>
                            <dd><a href="">MYSQL 索引</a></dd>
                            <dd><a href="">MYSQL 管理</a></dd>
                            <dd><a href="">MYSQL 全文搜索</a></dd>
                        </dl>
                    </li>
                    <li class="layui-nav-item"><a href="">社区</a></li>
                </ul>
            </div>
        </div>
    </div>
</div>

<div class="layui-container main">
    <div class="layui-row">
        <div class="layui-col-md9 layui-card left">
            <div class="layui-card-body">
                <div class="layui-breadcrumb">
                    <a href="#">首页</a>
                    <a href="#"><cite>开始使用MySQL</cite></a>
                </div>
                <div class="entry-content">
                    <p>如果您以前从未使用过MySQL，那么本节将帮助您快速开始使用MySQL。</p>
                    <dl class="fancy-list">
                        <dt><a href="http://www.mysqltutorial.org/what-is-mysql/"><span
                                style="vertical-align: inherit;"><span
                                style="vertical-align: inherit;">MySQL简介</span></span></a></dt>
                        <dd><span style="vertical-align: inherit;"><span style="vertical-align: inherit;">快速介绍数据库和MySQL作为关系数据库管理系统（RDBMS）</span></span>
                        </dd>
                        <dt><a href="http://www.mysqltutorial.org/install-mysql/"><span
                                style="vertical-align: inherit;"><span
                                style="vertical-align: inherit;">安装MySQL</span></span></a></dt>
                        <dd><span style="vertical-align: inherit;"><span style="vertical-align: inherit;">逐步向您展示如何在计算机上安装MySQL
                            Server，以进行本教程的练习。</span></span></dd>
                        <dt><a href="http://www.mysqltutorial.org/connect-to-mysql-server/"><span
                                style="vertical-align: inherit;"><span
                                style="vertical-align: inherit;">连接到MySQL服务器</span></span></a></dt>
                        <dd><span style="vertical-align: inherit;"><span style="vertical-align: inherit;">引导您完成使用mysql客户端程序连接到MySQL
                            Server的步骤。</span></span></dd>
                        <dt><a href="http://www.mysqltutorial.org/mysql-sample-database.aspx"><span
                                style="vertical-align: inherit;"><span
                                style="vertical-align: inherit;">下载一个MySQL示例数据库</span></span></a></dt>
                        <dd><span style="vertical-align: inherit;"><span style="vertical-align: inherit;">向您介绍一个名为classicmodels的示例数据库，并提供下载链接</span></span>
                        </dd>
                        <dt>
                            <a href="http://www.mysqltutorial.org/how-to-load-sample-database-into-mysql-database-server.aspx"><span
                                    style="vertical-align: inherit;"><span
                                    style="vertical-align: inherit;">加载样本数据库</span></span></a></dt>
                        <dd><span style="vertical-align: inherit;"><span style="vertical-align: inherit;">向您展示如何将classicmodels示例数据库加载到MySQL
                            Server。</span></span></dd>
                    </dl>
                </div>
            </div>


        </div>
        <div class="layui-col-md3 right">
            <div class="layui-card">
                <div class="layui-card-header">MYSQL快速启动</div>
                <div class="layui-card-body">
                    <a href="#"><div>MySQL是什么?</div></a>
                    <a href="#"><div>安装MySQL数据库服务器</div></a>
                    <a href="#"><div>连接到MySQL服务器</div></a>
                    <a href="#"><div>下载MySQL样本数据库</div></a>
                    <a href="#"><div>加载示例数据库</div></a>
                </div>
            </div>

            <div class="layui-card">
                <div class="layui-card-header">MYSQL数据操作</div>
                <div class="layui-card-body">
                    <a href="#"><div>SELECT</div></a>
                    <a href="#"><div>ORDER BY</div></a>
                    <a href="#"><div>WHERE</div></a>
                    <a href="#"><div>SELECT DISTINCT</div></a>
                    <a href="#"><div>AND</div></a>
                    <a href="#"><div>OR</div></a>
                    <a href="#"><div>IN</div></a>
                    <a href="#"><div>BETWEEN</div></a>
                    <a href="#"><div>LIKE</div></a>
                    <a href="#"><div>LIMIT</div></a>
                    <a href="#"><div>IS NULL</div></a>
                    <a href="#"><div>Table & Column Aliases</div></a>
                    <a href="#"><div>Joins</div></a>
                    <a href="#"><div>INNER JOIN</div></a>
                    <a href="#"><div>LEFT JOIN</div></a>
                    <a href="#"><div>RIGHT JOIN</div></a>
                    <a href="#"><div>Self Join</div></a>
                    <a href="#"><div>CROSS JOIN</div></a>
                    <a href="#"><div>GROUP BY</div></a>
                    <a href="#"><div>HAVING</div></a>
                    <a href="#"><div>ROLLUP</div></a>
                    <a href="#"><div>Subquery</div></a>
                    <a href="#"><div>Derived Tables</div></a>
                    <a href="#"><div>EXISTS</div></a>
                    <a href="#"><div>UNION</div></a>
                    <a href="#"><div>MINUS</div></a>
                    <a href="#"><div>INTERSECT</div></a>
                    <a href="#"><div>INSERT</div></a>
                    <a href="#"><div>Insert Multiple Rows</div></a>
                    <a href="#"><div>INSERT INTO SELECT</div></a>
                    <a href="#"><div>Insert On Duplicate Key Update</div></a>
                    <a href="#"><div>INSERT IGNORE</div></a>
                    <a href="#"><div>UPDATE</div></a>
                    <a href="#"><div>UPDATE JOIN</div></a>
                    <a href="#"><div>DELETE</div></a>
                    <a href="#"><div>DELETE JOIN</div></a>
                    <a href="#"><div>ON DELETE CASCADE</div></a>
                    <a href="#"><div>REPLACE</div></a>
                </div>
            </div>

            <div class="layui-card">
                <div class="layui-card-header">MYSQL数据定义</div>
                <div class="layui-card-body">
                 <a href="#"><div>Selecting Database</div></a>
                 <a href="#"><div>CREATE DATABASE</div></a>
                 <a href="#"><div>DROP DATABASE</div></a>
                 <a href="#"><div>Managing Databases</div></a>
                 <a href="#"><div>Storage Engines</div></a>
                 <a href="#"><div>Data Types</div></a>
                 <a href="#"><div>CREATE TABLE</div></a>
                 <a href="#"><div>Primary Key</div></a>
                 <a href="#"><div>Foreign Key</div></a>
                 <a href="#"><div>UNIQUE Constraint</div></a>
                 <a href="#"><div>CHECK Constraint</div></a>
                 <a href="#"><div>NOT NULL</div></a>
                 <a href="#"><div>Sequence</div></a>
                 <a href="#"><div>ALTER TABLE</div></a>
                 <a href="#"><div>ADD COLUMN</div></a>
                 <a href="#"><div>DROP COLUMN</div></a>
                 <a href="#"><div>RENAME TABLE</div></a>
                 <a href="#"><div>DROP TABLE</div></a>
                 <a href="#"><div>Temporary Tables</div></a>
                 <a href="#"><div>TRUNCATE TABLE</div></a>
                </div>
            </div>
        </div>
    </div>
</div>



<script src="/plugs/layui/layui.all.js"></script>
<script>
    var form = layui.form
        ,layer = layui.layer;
</script>
</body>
</html>