<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" type="text/css" href="/plugs/layui/css/layui.css"/>
    <link rel="stylesheet" type="text/css" href="/css/base.css?2"/>
    <link rel="stylesheet" href="//cdn.jsdelivr.net/gh/highlightjs/cdn-release@9.16.2/build/styles/agate.min.css">
    <style>
        .top{
            height: 80px;
        }
        .top .log{
            height: 70px;
            background: url(http://mysqltutorial.org//wp-content/uploads/2016/01/mysqltutorial.png) no-repeat left center;
        }
        .top .log a{
            display: block;
            float: left;
            min-height: 60px;
            text-indent: -9999px;
            width: 100%;
        }
        .top .nav{
            height: 80px;
            line-height: 80px;
        }

        .main{
            margin-top: 10px;
        }
        .main .left{
            width: 73%;
            margin-right: 2%;
        }
        .main .right{
            width: 25%;
        }
        .layadmin-serach-list li{
            display: flex;
            flex-direction: row;
            margin: 20px 0;
        }
        .layadmin-serach-list li .layui-serachlist-cover img{
            width: 60px;
        }
        .layadmin-serach-list li .layui-serachlist-text{
            margin: 0 10px;
        }

        .fancy-list dt{
            margin-top: 20px;
        }
        .entry-content ul{
            margin-left: 40px;
        }
        .entry-content ul>li:before {
            list-style-type: none;
            content: '';
            margin-left: -.7em;
            margin-top: 9px;
            width: 5px;
            height: 5px;
            background: #fa5b0f;
            position: absolute;
        }
        .main .left p{
            margin: 10px 0;
        }
    </style>
</head>
<body>

<div class="top layui-bg-green">
    <div class="layui-container">
        <div class="layui-row">
            <div class="layui-col-md3 log">
                <a href="http://www.mysqltutorial.org/">MySQL Tutorial</a>
            </div>
            <div class="layui-col-md8 layui-col-lg-offset1">
                <ul class="layui-nav layui-bg-green nav" lay-filter="">
                    <li class="layui-nav-item"><a href="">首页</a></li>
                    <li class="layui-nav-item"><a href="">开始</a></li>
                    <li class="layui-nav-item"><a href="">基础</a></li>
                    <li class="layui-nav-item">
                        <a href="javascript:;">高级</a>
                        <dl class="layui-nav-child"> <!-- 二级菜单 -->
                            <dd><a href="">MYSQL 存储过程</a></dd>
                            <dd><a href="">MYSQL 视图</a></dd>
                            <dd><a href="">MYSQL 触发器</a></dd>
                            <dd><a href="">MYSQL 事件</a></dd>
                            <dd><a href="">MYSQL 索引</a></dd>
                            <dd><a href="">MYSQL 管理</a></dd>
                            <dd><a href="">MYSQL 全文搜索</a></dd>
                        </dl>
                    </li>
                    <li class="layui-nav-item"><a href="">社区</a></li>
                </ul>
            </div>
        </div>
    </div>
</div>

<div class="layui-container main">
    <div class="layui-row">
        <div class="layui-col-md9 layui-card left">
            <div class="layui-card-body">
                <div class="layui-breadcrumb">
                    <a href="#">首页</a>
                    <a href="#"><cite>开始使用MySQL</cite></a>
                </div>
                <div class="entry-content"><p><strong><span style="vertical-align: inherit;"><span
                        style="vertical-align: inherit;">简介</span></span></strong><em><span
                        style="vertical-align: inherit;"><span
                        style="vertical-align: inherit;">：</span></span></em><span
                        style="vertical-align: inherit;"><span
                        style="vertical-align: inherit;">在本教程中，您将学习如何使用该</span></span><code>mysql</code><span
                        style="vertical-align: inherit;"><span style="vertical-align: inherit;">程序</span><span
                        style="vertical-align: inherit;">将示例数据库加载到MySQL Server中</span><span
                        style="vertical-align: inherit;">。</span></span></p>
                    <h3><span style="vertical-align: inherit;"><span style="vertical-align: inherit;">第一步</span></span>
                    </h3>
                    <p><span style="vertical-align: inherit;"></span><code>classicmodels</code><span
                            style="vertical-align: inherit;"><span style="vertical-align: inherit;">从</span></span><a
                            title="MySQL样本数据库" href="http://www.mysqltutorial.org/mysql-sample-database.aspx"><span
                            style="vertical-align: inherit;"><span
                            style="vertical-align: inherit;">MySQL示例数据库</span></span></a><span
                            style="vertical-align: inherit;"><span style="vertical-align: inherit;">部分</span><span
                            style="vertical-align: inherit;">下载</span><a title="MySQL样本数据库"
                                                                         href="http://www.mysqltutorial.org/mysql-sample-database.aspx"><span
                            style="vertical-align: inherit;">数据库</span></a><span
                            style="vertical-align: inherit;">。</span></span></p>
                    <h3><span style="vertical-align: inherit;"><span style="vertical-align: inherit;">第二步</span></span>
                    </h3>
                    <p><span style="vertical-align: inherit;"><span
                            style="vertical-align: inherit;">将下载的文件解压缩到一个临时文件夹中。</span><span
                            style="vertical-align: inherit;">您可以使用所需的任何文件夹。</span><span
                            style="vertical-align: inherit;">为简单起见，我们将文件解压缩到文件</span></span><code>C:\temp</code><span
                            style="vertical-align: inherit;"><span style="vertical-align: inherit;">
                        &nbsp;夹中。</span></span></p>
                    <p><span style="vertical-align: inherit;"><span style="vertical-align: inherit;">如果您使用其他操作系统，例如macOS，Linux或Unix，请随时将其解压缩到所需的任何目录。</span></span>
                    </p>
                    <h3><span style="vertical-align: inherit;"><span style="vertical-align: inherit;">第三步</span></span>
                    </h3>
                    <p><span style="vertical-align: inherit;"><span
                            style="vertical-align: inherit;">使用</span></span><code>mysql</code><span
                            style="vertical-align: inherit;"><span style="vertical-align: inherit;">客户端程序</span><span
                            style="vertical-align: inherit;">连接到MySQL服务器</span><span
                            style="vertical-align: inherit;">。</span><span
                            style="vertical-align: inherit;">该</span></span><code>mysql</code><span
                            style="vertical-align: inherit;"><span
                            style="vertical-align: inherit;">程序位于</span></span><code>bin</code><span
                            style="vertical-align: inherit;"><span
                            style="vertical-align: inherit;">MySQL安装文件夹</span><span
                            style="vertical-align: inherit;">的</span><span style="vertical-align: inherit;">目录中。</span></span>
                    </p>
                    <div id="crayon-5dd5f50516cfb516763240"
                         class="crayon-syntax crayon-theme-coy-copied crayon-span-sourcecodepro crayon-os-pc print-yes notranslate"
                         data-settings=" no-popup minimize scroll-mouseover wrap"
                         style=" margin-top: 12px; margin-bottom: 12px; span-size: 14px !important; line-height: 19px !important;">
                        <div class="crayon-plain-wrap"></div>
                        <pre><code class="Shell Session">&gt; mysql -u root -p
Enter password: ********</code></pre>
                    </div>
                    <p><span style="vertical-align: inherit;"><span style="vertical-align: inherit;">您需要输入</span></span><code>root</code><span
                            style="vertical-align: inherit;"><span style="vertical-align: inherit;">用户帐户</span><span
                            style="vertical-align: inherit;">的密码</span><span
                            style="vertical-align: inherit;">才能登录。</span></span></p>
                    <h3><span style="vertical-align: inherit;"><span style="vertical-align: inherit;">第四步</span></span>
                    </h3>
                    <p><span style="vertical-align: inherit;"><span
                            style="vertical-align: inherit;">使用以下</span></span><code>source</code><span
                            style="vertical-align: inherit;"><span
                            style="vertical-align: inherit;">命令将数据加载到MySQL服务器中：</span></span></p>
                    <div id="crayon-5dd5f50516d05784651929"
                         class="crayon-syntax crayon-theme-coy-copied crayon-span-sourcecodepro crayon-os-pc print-yes notranslate"
                         data-settings=" no-popup minimize scroll-mouseover wrap"
                         style=" margin-top: 12px; margin-bottom: 12px; span-size: 14px !important; line-height: 19px !important;">
                        <div class="crayon-plain-wrap"></div>
                        <pre><code class="Shell Session">mysql&gt; source c:\temp\mysqlsampledatabase.sql</code></pre>
                    </div>
                    <p></p>
                    <h3><span style="vertical-align: inherit;"><span style="vertical-align: inherit;">第五步</span></span>
                    </h3>
                    <p><span style="vertical-align: inherit;"><span
                            style="vertical-align: inherit;">使用</span></span><code><a
                            href="http://www.mysqltutorial.org/mysql-show-databases/">SHOW DATABASES</a></code><span
                            style="vertical-align: inherit;"><span
                            style="vertical-align: inherit;">命令列出当前服务器中的所有数据库：</span></span></p>
                    <div id="crayon-5dd5f50516d07566051482"
                         class="crayon-syntax crayon-theme-coy-copied crayon-span-sourcecodepro crayon-os-pc print-yes notranslate"
                         data-settings=" no-popup minimize scroll-mouseover wrap"
                         style=" margin-top: 12px; margin-bottom: 12px; span-size: 14px !important; line-height: 19px !important;">
                        <div class="crayon-plain-wrap"></div>
                        <pre><code class="Shell Session">mysql&gt; show databases;</code></pre>
                    </div>
                    <p><span style="vertical-align: inherit;"><span
                            style="vertical-align: inherit;">输出将类似于以下内容，其中包括新创建的</span></span><code>classicmodels</code><span
                            style="vertical-align: inherit;"><span style="vertical-align: inherit;">数据库：</span></span>
                    </p>
                    <div id="crayon-5dd5f50516d09135516754"
                         class="crayon-syntax crayon-theme-coy-copied crayon-span-sourcecodepro crayon-os-pc print-yes notranslate"
                         data-settings=" no-popup minimize scroll-mouseover wrap"
                         style=" margin-top: 12px; margin-bottom: 12px; span-size: 14px !important; line-height: 19px !important;">
                        <div class="crayon-plain-wrap"></div>
                        <pre><code class="Shell Session">+--------------------+
| Database           |
+--------------------+
| classicmodels      |
| information_schema |
| mysql              |
| performance_schema |
| sys                |
+--------------------+</code></pre>
                    </div>
                    <p><span style="vertical-align: inherit;"><span
                            style="vertical-align: inherit;">在本教程中，您逐步学习了如何使用该</span></span><code>mysql</code><span
                            style="vertical-align: inherit;"><span style="vertical-align: inherit;">工具</span><span
                            style="vertical-align: inherit;">将示例数据库加载到MySQL服务器中</span><span
                            style="vertical-align: inherit;">。</span></span></p>
                </div>
            </div>


        </div>
        <div class="layui-col-md3 right">
            <div class="layui-card">
                <div class="layui-card-header">MYSQL快速启动</div>
                <div class="layui-card-body">
                    <a href="#"><div>MySQL是什么?</div></a>
                    <a href="#"><div>安装MySQL数据库服务器</div></a>
                    <a href="#"><div>连接到MySQL服务器</div></a>
                    <a href="#"><div>下载MySQL样本数据库</div></a>
                    <a href="#"><div>加载示例数据库</div></a>
                </div>
            </div>

            <div class="layui-card">
                <div class="layui-card-header">MYSQL数据操作</div>
                <div class="layui-card-body">
                    <a href="#"><div>SELECT</div></a>
                    <a href="#"><div>ORDER BY</div></a>
                    <a href="#"><div>WHERE</div></a>
                    <a href="#"><div>SELECT DISTINCT</div></a>
                    <a href="#"><div>AND</div></a>
                    <a href="#"><div>OR</div></a>
                    <a href="#"><div>IN</div></a>
                    <a href="#"><div>BETWEEN</div></a>
                    <a href="#"><div>LIKE</div></a>
                    <a href="#"><div>LIMIT</div></a>
                    <a href="#"><div>IS NULL</div></a>
                    <a href="#"><div>Table & Column Aliases</div></a>
                    <a href="#"><div>Joins</div></a>
                    <a href="#"><div>INNER JOIN</div></a>
                    <a href="#"><div>LEFT JOIN</div></a>
                    <a href="#"><div>RIGHT JOIN</div></a>
                    <a href="#"><div>Self Join</div></a>
                    <a href="#"><div>CROSS JOIN</div></a>
                    <a href="#"><div>GROUP BY</div></a>
                    <a href="#"><div>HAVING</div></a>
                    <a href="#"><div>ROLLUP</div></a>
                    <a href="#"><div>Subquery</div></a>
                    <a href="#"><div>Derived Tables</div></a>
                    <a href="#"><div>EXISTS</div></a>
                    <a href="#"><div>UNION</div></a>
                    <a href="#"><div>MINUS</div></a>
                    <a href="#"><div>INTERSECT</div></a>
                    <a href="#"><div>INSERT</div></a>
                    <a href="#"><div>Insert Multiple Rows</div></a>
                    <a href="#"><div>INSERT INTO SELECT</div></a>
                    <a href="#"><div>Insert On Duplicate Key Update</div></a>
                    <a href="#"><div>INSERT IGNORE</div></a>
                    <a href="#"><div>UPDATE</div></a>
                    <a href="#"><div>UPDATE JOIN</div></a>
                    <a href="#"><div>DELETE</div></a>
                    <a href="#"><div>DELETE JOIN</div></a>
                    <a href="#"><div>ON DELETE CASCADE</div></a>
                    <a href="#"><div>REPLACE</div></a>
                </div>
            </div>

            <div class="layui-card">
                <div class="layui-card-header">MYSQL数据定义</div>
                <div class="layui-card-body">
                 <a href="#"><div>Selecting Database</div></a>
                 <a href="#"><div>CREATE DATABASE</div></a>
                 <a href="#"><div>DROP DATABASE</div></a>
                 <a href="#"><div>Managing Databases</div></a>
                 <a href="#"><div>Storage Engines</div></a>
                 <a href="#"><div>Data Types</div></a>
                 <a href="#"><div>CREATE TABLE</div></a>
                 <a href="#"><div>Primary Key</div></a>
                 <a href="#"><div>Foreign Key</div></a>
                 <a href="#"><div>UNIQUE Constraint</div></a>
                 <a href="#"><div>CHECK Constraint</div></a>
                 <a href="#"><div>NOT NULL</div></a>
                 <a href="#"><div>Sequence</div></a>
                 <a href="#"><div>ALTER TABLE</div></a>
                 <a href="#"><div>ADD COLUMN</div></a>
                 <a href="#"><div>DROP COLUMN</div></a>
                 <a href="#"><div>RENAME TABLE</div></a>
                 <a href="#"><div>DROP TABLE</div></a>
                 <a href="#"><div>Temporary Tables</div></a>
                 <a href="#"><div>TRUNCATE TABLE</div></a>
                </div>
            </div>
        </div>
    </div>
</div>



<script src="./plugs/layui/layui.all.js"></script>
<script src="//cdn.jsdelivr.net/gh/highlightjs/cdn-release@9.16.2/build/highlight.min.js"></script>
<script>hljs.initHighlightingOnLoad();</script>
</body>
</html>